export const SliderData = [
   {
      id: "F1",
      name: "Beef Noodles",
      serial: "Featured Dish 1",
      category: "Noodles",
      type: "Featured Meal",
      imgURL: "https://i.ibb.co/kcQ32bd/home-img-1.png",
      ingredients: "bon, beef, cheese, latus, sausage",
      country: "",
      price: 400,
      rating: 4.6,
      vote: "1444",
   },
   {
      id: "F2",
      name: "Chicken Tandoori",
      serial: "Featured Dish 2",
      category: "Chicken",
      type: "Featured Meal",
      imgURL: "https://i.ibb.co/VNqW1QT/home-img-2.png",
      ingredients: "bon, beef, cheese, latus, sausage",
      country: "",
      price: 499,
      rating: 4.5,
      vote: "1515",
   },
   {
      id: "F3",
      name: "Dominos Pizza",
      serial: "Featured Dish 3",
      category: "Pizza",
      type: "Featured Meal",
      imgURL: "https://i.ibb.co/sHZFKHJ/home-img-3.png",
      ingredients: "bon, beef, cheese, latus, sausage",
      country: "",
      price: 599,
      rating: 4.5,
      vote: "1334",
   },
];
